version: 2
updates:
  # npm依存関係の自動更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "naoto.kato"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # メジャーバージョンアップは手動で行う
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  
  # GitHub Actionsの自動更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "naoto.kato"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"