name: CI

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm build:all

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Run tests - Common package
        run: pnpm test:common
        env:
          NODE_ENV: test
          CI: true
      
      - name: Run tests - Core package
        run: pnpm test:core
        env:
          NODE_ENV: test
          CI: true

      - name: Run tests - Audio package
        run: pnpm test:audio
        env:
          NODE_ENV: test
          CI: true

      - name: Run tests - CLI package
        run: pnpm test:cli
        env:
          NODE_ENV: test
          CI: true

      - name: Run tests - MCP package
        run: pnpm test:mcp
        env:
          NODE_ENV: test
          CI: true

      - name: Run tests - MCP Debug package
        run: pnpm test:mcp-debug
        env:
          NODE_ENV: test
          CI: true

      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          NODE_ENV: test
          CI: true
          COEIRO_TEST_MODE: true