name: E2E Tests

on:
  pull_request:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.js'
      - 'package*.json'
      - '.github/workflows/e2e-tests.yml'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable debug mode'
        required: false
        default: false

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run all E2E tests
        run: npm run test:e2e
        env:
          COEIRO_TEST_MODE: true
          COEIROINK_OPERATOR_CONFIG_PATH: /tmp/test-operator-config-${{ github.run_id }}.json
          DEBUG: ${{ github.event.inputs.debug_enabled }}
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            test-results/
            /tmp/test-operator-config-*.json
          retention-days: 7