name: Auto Version on Release Branch

on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    name: Apply Changeset Version
    runs-on: ubuntu-latest
    # 既にVersion Packagesコミットがある場合はスキップ
    if: "!contains(github.event.head_commit.message, 'Version Packages')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch main branch
        run: |
          git fetch origin main:main
          echo "Available branches:"
          git branch -a

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for changesets
        id: changesets
        run: |
          # Check if changesets exist in the .changeset directory
          if ls .changeset/*.md 2>/dev/null | grep -v README.md > /dev/null; then
            echo "Changesets found in .changeset directory"
            echo "has_changesets=true" >> $GITHUB_OUTPUT
          else
            echo "No changesets found in .changeset directory"
            echo "has_changesets=false" >> $GITHUB_OUTPUT
          fi

      - name: Apply version updates
        if: steps.changesets.outputs.has_changesets == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Apply changeset version
          npx changeset version

          # Extract version from branch name (release/x.x.x)
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" =~ ^release/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"

            # Update root package.json with the version from branch name
            node -e "
              const fs = require('fs');
              const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
              pkg.version = '$VERSION';
              fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
            "
            echo "Updated root package.json to version $VERSION (from branch name)"
          else
            echo "Warning: Could not extract version from branch name: $BRANCH_NAME"
          fi

          # Commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Version Packages"
            git push
          fi

      - name: Create or update PR
        if: steps.changesets.outputs.has_changesets == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from root package.json (which now has the highest version)
          VERSION=$(node -p "require('./package.json').version")
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Check if PR already exists
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            # Get package status
            PACKAGE_STATUS=$(npx changeset status --output /dev/stdout | grep -A 100 'packages to be bumped' || echo 'See changeset status for details')

            # Create new PR
            gh pr create \
              --base main \
              --head "$BRANCH_NAME" \
              --title "Release v$VERSION" \
              --body "## 🚀 Release v$VERSION

          This PR will automatically publish packages to npm when merged.

          ### Packages to be released:
          $PACKAGE_STATUS

          ---
          ⚠️ **Merging this PR will automatically publish to npm**"
          else
            echo "PR #$PR_NUMBER already exists"
          fi
