name: Release

# 緊急時の手動リリース用ワークフロー
# 通常はrelease-version.yml（PR作成）とrelease-branch.yml（npm公開）を使用
# このワークフローは手動実行のみで、緊急時のバックアップとして残しています
on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Release mode'
        required: true
        default: 'pr'
        type: choice
        options:
          - pr      # Create release PR only
          - publish # Directly publish without PR
      createGithubRelease:
        description: 'Create GitHub Release'
        required: false
        default: true
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y libasound2-dev
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build:all

      - name: Run tests
        run: pnpm test

      - name: Create Release Pull Request
        if: github.event.inputs.mode == 'pr' || github.event.inputs.mode == ''
        id: changesets_pr
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          commit: 'chore: release packages'
          title: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: github.event.inputs.mode == 'publish'
        id: changesets_publish
        run: |
          pnpm changeset:version
          git add .
          git commit -m "chore: version packages" || echo "No changes to commit"
          pnpm publish -r --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: github.event.inputs.mode == 'publish' && github.event.inputs.createGithubRelease == 'true'
        run: |
          # Get the latest version from package.json
          VERSION=$(node -p "require('./package.json').version")
          gh release create "v${VERSION}" \
            --title "Release v${VERSION}" \
            --notes "See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details." \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}